name: CI-on-push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
        image: 'docker://michaelspark/ses'
    steps:
    - uses: actions/checkout@v2
      with:
        path: ./longburn/
    - name: Build
      run: ls /ses/bin/
