name: CI-on-push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
        image: 'docker://michaelspark/ses'
    steps:
    - name: Build
      run: /ses/bin/emBuild -config Debug -project P3 -rebuild ./longburn.emProject
